server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/payments_db
    username: payments
    password: payments_pass
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    spring:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.orbitamarket.common.dto"
        spring.json.value.default.type: "com.orbitamarket.common.dto.OrderPaymentRequestedEvent"
    # ... остальное без изменений
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    template:
      default-topic: order.payment.requested
logging:
  level:
    org.springframework.web: DEBUG
